#!/usr/bin/env bash
#
# One command to test PND Editions fully locally before deploying.
#
#   pnpm dev:editions
#     (or: bash scripts/dev-editions.sh)
#
# What it does:
#   1. Finds a free port (won't collide with an Anvil you already have on 8545).
#   2. Starts an Anvil mainnet fork on a custom chain id (31339 — the same id
#      the web app's wagmi config registers for the fork chain) with
#      auto-impersonate on. Forking mainnet means Multicall3 (0xcA11…) and ENS
#      are present, so every PND surface works, not just editions.
#   3. Deploys the editions system (renderer + implementation + factory).
#   4. Funds an impersonated wallet so you can click through create + mint with
#      NO real wallet or signing — the app auto-connects as that address.
#   5. Writes apps/web/.env.development.local (layers over your real .env.local
#      in `next dev`, gitignored) with the fork settings + factory address.
#   6. Starts the web dev server.
#
# When you Ctrl+C, Anvil is stopped. To fully restore production env, delete
# apps/web/.env.development.local (the script also prints this reminder).
#
# Overridable via env:
#   FORK_RPC      upstream RPC to fork (default: free publicnode)
#   IMPERSONATE   address you act as (default: Anvil account 0)
#   WEB_PORT      Next dev port (default: 3000)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Foundry on PATH even if the caller's shell doesn't have it.
if ! command -v anvil >/dev/null 2>&1; then
  export PATH="$HOME/.foundry/bin:$PATH"
fi
command -v anvil >/dev/null 2>&1 || { echo "error: anvil not found (install Foundry: https://getfoundry.sh)"; exit 1; }

# Free public RPC for the fork (per repo RPC policy: don't burn paid CU on
# forks). Anvil caches state locally, so the upstream sees only a trickle.
FORK_RPC="${FORK_RPC:-https://ethereum-rpc.publicnode.com}"
CHAIN_ID=31339                      # must match wagmi.ts forkChain id
IMPERSONATE="${IMPERSONATE:-0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}"  # Anvil acct 0

# Web dev port: honor an explicit WEB_PORT, else first free port >= 3000 so we
# don't collide with other dev servers (Next would otherwise fail EADDRINUSE).
if [ -z "${WEB_PORT:-}" ]; then
  WEB_PORT=3000
  while lsof -iTCP:"$WEB_PORT" -sTCP:LISTEN >/dev/null 2>&1; do WEB_PORT=$((WEB_PORT + 1)); done
fi

# 1) free anvil port, starting above the common 8545 dev node.
PORT=8546
while lsof -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; do PORT=$((PORT + 1)); done
RPC="http://127.0.0.1:$PORT"

echo "▸ Anvil fork: $RPC  (chain id $CHAIN_ID, forking $FORK_RPC)"
anvil \
  --fork-url "$FORK_RPC" \
  --chain-id "$CHAIN_ID" \
  --port "$PORT" \
  --host 127.0.0.1 \
  --auto-impersonate \
  --silent &
ANVIL_PID=$!

cleanup() { kill "$ANVIL_PID" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

# wait for readiness
for _ in $(seq 1 60); do
  if cast block-number --rpc-url "$RPC" >/dev/null 2>&1; then break; fi
  sleep 0.25
done
cast block-number --rpc-url "$RPC" >/dev/null 2>&1 || { echo "error: Anvil did not come up"; exit 1; }

# 2) fund the impersonated wallet (10000 ETH) so create/mint never run out of gas.
cast rpc anvil_setBalance "$IMPERSONATE" 0x21e19e0c9bab2400000 --rpc-url "$RPC" >/dev/null

# 3) deploy the editions system.
echo "▸ Deploying editions contracts…"
DEPLOY_OUT="$(cd contracts && forge script script/DeployEditions.s.sol \
  --rpc-url "$RPC" --broadcast --sender "$IMPERSONATE" --unlocked 2>&1)" || {
  echo "$DEPLOY_OUT" | tail -30
  echo "error: deploy failed"
  exit 1
}
FACTORY="$(echo "$DEPLOY_OUT" | grep -i "PNDEditionsFactory:" | grep -oE "0x[0-9a-fA-F]{40}" | head -1)"
[ -n "$FACTORY" ] || { echo "$DEPLOY_OUT" | tail -30; echo "error: could not parse factory address"; exit 1; }
echo "▸ Factory deployed: $FACTORY"

# 4) write dev env (non-destructive: .env.development.local wins over
#    .env.local only in `next dev`, and is gitignored).
ENV_DEV="apps/web/.env.development.local"
cat > "$ENV_DEV" <<EOF
# Auto-generated by scripts/dev-editions.sh for local fork testing.
# Delete this file to restore your normal dev env.
NEXT_PUBLIC_USE_LOCAL_RPC=1
NEXT_PUBLIC_ANVIL_RPC_URL=$RPC
NEXT_PUBLIC_PND_EDITIONS_FACTORY=$FACTORY
NEXT_PUBLIC_DEV_IMPERSONATE=$IMPERSONATE
EOF
echo "▸ Wrote $ENV_DEV  (delete it to restore prod env)"

echo
echo "──────────────────────────────────────────────────────────────"
echo "  PND Editions local test is ready."
echo "    Fork RPC : $RPC  (chain id $CHAIN_ID)"
echo "    Factory  : $FACTORY"
echo "    Acting as: $IMPERSONATE  (auto-connected, no wallet needed)"
echo
echo "    Open:  http://localhost:$WEB_PORT/editions/new"
echo "    Stop:  Ctrl+C  (then: rm $ENV_DEV)"
echo "──────────────────────────────────────────────────────────────"
echo

# 5) start the web dev server in the foreground (Ctrl+C stops both).
# Call `next` directly (not `pnpm run dev -- --port`): pnpm forwards `--`
# literally, which Next then treats as the project dir.
pnpm --filter @pin/web exec next dev --turbopack --port "$WEB_PORT"
