#!/usr/bin/env bash
#
# One command to test the Releases protocol fully locally before deploying.
#
#   pnpm dev:releases
#     (or: bash scripts/dev-releases.sh)
#
# Same harness as scripts/dev-editions.sh (see its comments for the why):
# Anvil mainnet fork on chain id 31339 with auto-impersonate, deploy the
# ReleaseFactory, write apps/web/.env.development.local, start the web dev
# server with the wallet auto-connected.
#
# Overridable via env:
#   FORK_RPC      upstream RPC to fork (default: free publicnode)
#   IMPERSONATE   address you act as (default: Anvil account 0)
#   WEB_PORT      Next dev port (default: first free port >= 3000)
#   SURFACE       surface address PND's pages pass on mints
#                 (default: Anvil account 1, so the fee leg is visible)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v anvil >/dev/null 2>&1; then
  export PATH="$HOME/.foundry/bin:$PATH"
fi
command -v anvil >/dev/null 2>&1 || { echo "error: anvil not found (install Foundry: https://getfoundry.sh)"; exit 1; }

FORK_RPC="${FORK_RPC:-https://ethereum-rpc.publicnode.com}"
CHAIN_ID=31339                      # must match wagmi.ts forkChain id
IMPERSONATE="${IMPERSONATE:-0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}"  # Anvil acct 0
SURFACE="${SURFACE:-0x70997970C51812dc3A010C7d01b50e0d17dc79C8}"          # Anvil acct 1

if [ -z "${WEB_PORT:-}" ]; then
  WEB_PORT=3000
  while lsof -iTCP:"$WEB_PORT" -sTCP:LISTEN >/dev/null 2>&1; do WEB_PORT=$((WEB_PORT + 1)); done
fi

PORT=8546
while lsof -iTCP:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; do PORT=$((PORT + 1)); done
RPC="http://127.0.0.1:$PORT"

echo "▸ Anvil fork: $RPC  (chain id $CHAIN_ID, forking $FORK_RPC)"
anvil \
  --fork-url "$FORK_RPC" \
  --chain-id "$CHAIN_ID" \
  --port "$PORT" \
  --host 127.0.0.1 \
  --auto-impersonate \
  --silent &
ANVIL_PID=$!

cleanup() { kill "$ANVIL_PID" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM

for _ in $(seq 1 60); do
  if cast block-number --rpc-url "$RPC" >/dev/null 2>&1; then break; fi
  sleep 0.25
done
cast block-number --rpc-url "$RPC" >/dev/null 2>&1 || { echo "error: Anvil did not come up"; exit 1; }

cast rpc anvil_setBalance "$IMPERSONATE" 0x21e19e0c9bab2400000 --rpc-url "$RPC" >/dev/null

echo "▸ Deploying ReleaseFactory…"
DEPLOY_OUT="$(cd contracts && forge script script/DeployReleases.s.sol \
  --rpc-url "$RPC" --broadcast --sender "$IMPERSONATE" --unlocked 2>&1)" || {
  echo "$DEPLOY_OUT" | tail -30
  echo "error: deploy failed"
  exit 1
}
FACTORY="$(echo "$DEPLOY_OUT" | grep -i "ReleaseFactory:" | grep -oE "0x[0-9a-fA-F]{40}" | head -1)"
[ -n "$FACTORY" ] || { echo "$DEPLOY_OUT" | tail -30; echo "error: could not parse factory address"; exit 1; }
echo "▸ Factory deployed: $FACTORY"

ENV_DEV="apps/web/.env.development.local"
cat > "$ENV_DEV" <<EOF
# Auto-generated by scripts/dev-releases.sh for local fork testing.
# Delete this file to restore your normal dev env.
NEXT_PUBLIC_USE_LOCAL_RPC=1
NEXT_PUBLIC_ANVIL_RPC_URL=$RPC
NEXT_PUBLIC_RELEASE_FACTORY=$FACTORY
NEXT_PUBLIC_PND_SURFACE_ADDRESS=$SURFACE
NEXT_PUBLIC_DEV_IMPERSONATE=$IMPERSONATE
EOF
echo "▸ Wrote $ENV_DEV  (delete it to restore prod env)"

echo
echo "──────────────────────────────────────────────────────────────"
echo "  Releases local test is ready."
echo "    Fork RPC : $RPC  (chain id $CHAIN_ID)"
echo "    Factory  : $FACTORY"
echo "    Surface  : $SURFACE  (collects the flat fee on served mints)"
echo "    Acting as: $IMPERSONATE  (auto-connected, no wallet needed)"
echo
echo "    Open:  http://localhost:$WEB_PORT/releases/new"
echo "    Stop:  Ctrl+C  (then: rm $ENV_DEV)"
echo "──────────────────────────────────────────────────────────────"
echo

pnpm --filter @pin/web exec next dev --turbopack --port "$WEB_PORT"
