/**
 * PND onchain-protocols reference-docs generator.
 *
 * Merges three inputs into an API-style reference:
 *   1. Checked-in ABIs            packages/abi/src/*.ts  (via @pin/abi)
 *   2. Mainnet deployments        contracts/deployments.mainnet.json (addresses)
 *   3. Hand-authored prose        docs/reference/_prose/<Name>.md
 *      + hand-written pages       docs/reference/_pages/**
 *
 * The reference is organized into GROUPS. Two are shared (Introduction,
 * Off-chain); the rest are protocols (Collections, Auctions, and more as they
 * ship). Each protocol is a self-contained doc set: an overview, concept pages,
 * per-contract references, guides, and its own cross-cutting indexes (access
 * control, errors, events). URLs are namespaced by group:
 *   /docs/introduction/overview
 *   /docs/collections/contracts/sovereign-collection
 *   /docs/auctions/contracts/sovereign-auction-house
 *
 * Outputs:
 *   docs/reference/<group>/<section?>/<slug>.md   final pages (GENERATED)
 *   apps/web/src/lib/docs/manifest.json           grouped sidebar tree + metadata
 *   apps/web/src/lib/docs/content.json            pre-rendered highlighted HTML
 *   apps/web/public/abis/<Name>.json              ABI copies for integrators/agents
 *   apps/web/public/protocol-manifest.json        machine-readable entry point
 *   apps/web/public/llms.txt                      LLM orientation file
 *   apps/web/public/docs-search-index.json        client-side search corpus
 *
 * The generator is deliberately strict: every ABI function/event/error must
 * have a prose block, every state-changing function must declare its access
 * model, and prose blocks naming unknown ABI items fail the build. Signatures
 * can never drift because they are derived, not written.
 *
 * The contracts are pre-deploy: unresolved {{addr:*}} tokens render as a
 * `<SCREAMING_SNAKE_ADDRESS>` placeholder (with a build-time notice) rather
 * than failing the build. Fill contracts/deployments.mainnet.json at launch.
 *
 * Prose format: see docs/reference/_prose/SPEC.md.
 */
import {existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {Marked} from 'marked';
import {createHighlighter, type Highlighter} from 'shiki';
// Import the workspace ABIs by relative path, not the bare `@pin/abi` specifier:
// this script runs from the repo root, whose node_modules does not link the
// workspace package, so a bare import can resolve upward to a stale sibling
// checkout. The relative path always reads this tree's own ABIs.
import * as abis from '../packages/abi/src/index.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PROSE_DIR = join(ROOT, 'docs', 'reference', '_prose');
const ASSETS_DIR = join(ROOT, 'docs', 'reference', '_assets');
const PAGES_DIR = join(ROOT, 'docs', 'reference', '_pages');
const OUT_DIR = join(ROOT, 'docs', 'reference');
const APP_DOCS_DIR = join(ROOT, 'apps', 'web', 'src', 'lib', 'docs');
const APP_PUBLIC_DIR = join(ROOT, 'apps', 'web', 'public');

const DEPLOYMENTS_PATH = join(ROOT, 'contracts', 'deployments.mainnet.json');
const DEPLOYMENTS = JSON.parse(readFileSync(DEPLOYMENTS_PATH, 'utf8')) as Record<string, string | number>;

/** Canonical production origin. Machine-readable outputs name this domain so an
 *  external agent has an absolute base. In-page markdown links stay relative. */
const SITE_ORIGIN = 'https://pnd.ripe.wtf';
const REFERENCE_TITLE = 'PND protocol reference';

const GENERATED_BANNER = (src: string) =>
    `<!-- GENERATED by scripts/generate-docs.ts from ${src}. Do not edit this file directly. -->\n\n`;

// ── ABI registry (checked-in @pin/abi exports, keyed by contract name) ──

const ABI_BY_NAME: Record<string, AbiItem[]> = {
    Surface: abis.surfaceAbi as unknown as AbiItem[],
    SurfaceFactory: abis.surfaceFactoryAbi as unknown as AbiItem[],
    FixedPriceMinter: abis.fixedPriceMinterAbi as unknown as AbiItem[],
    DefaultRenderer: abis.defaultRendererAbi as unknown as AbiItem[],
    ScriptyRenderer: abis.scriptyRendererAbi as unknown as AbiItem[],
    RenderAssets: abis.renderAssetsAbi as unknown as AbiItem[],
    IPriceStrategy: abis.iPriceStrategyAbi as unknown as AbiItem[],
    IRenderer: abis.iRendererAbi as unknown as AbiItem[],
    ISurfaceView: abis.iSurfaceViewAbi as unknown as AbiItem[],
    IPreviewRenderer: abis.iPreviewRendererAbi as unknown as AbiItem[],
    SovereignAuctionHouse: abis.sovereignAuctionHouseAbi as unknown as AbiItem[],
    SovereignAuctionHouseFactory: abis.sovereignAuctionHouseFactoryAbi as unknown as AbiItem[],
};

// ── Page plan ──────────────────────────────────────────────────────────

type PageKind = 'singleton' | 'clone' | 'interface';

interface ContractPage {
    name: string; // ABI registry key + prose file name
    slug: string;
    /** Key into deployments.mainnet.json; null = no single canonical address. */
    deploymentsKey: string | null;
    kind: PageKind;
    /** Header note for clone/interface pages, or a pre-deploy singleton note. */
    note?: string;
}

interface HandPageSpec {
    section: string; // '' | 'concepts' | 'guides' | 'reference'
    slug: string;
    file: string; // path under _pages/
}

interface Protocol {
    id: string; // url group segment
    title: string;
    blurb: string; // one-liner used in the suite overview + llms.txt
    overview: string; // _pages file for the protocol overview (section '')
    concepts: HandPageSpec[];
    contracts: ContractPage[];
    guides: HandPageSpec[];
    referencePages: HandPageSpec[]; // hand pages that live in the reference section
}

const PROTOCOLS: Protocol[] = [
    {
        id: 'collections',
        title: 'Collections',
        blurb: 'Artist-owned ERC721 collections: a thin token core (ownership, per-token seed, renderer, royalty, supply cap, three one-way locks) where every mint goes through an authorized minter, with a canonical fixed-price/referral minter wired by the factory.',
        overview: 'collections/overview.md',
        concepts: [
            {section: 'concepts', slug: 'four-slots', file: 'collections/concepts/four-slots.md'},
            {section: 'concepts', slug: 'id-modes', file: 'collections/concepts/id-modes.md'},
            {section: 'concepts', slug: 'mint-marks-and-entropy', file: 'collections/concepts/mint-marks-and-entropy.md'},
            {section: 'concepts', slug: 'types', file: 'collections/concepts/types.md'},
        ],
        contracts: [
            {
                name: 'Surface',
                slug: 'surface',
                deploymentsKey: null,
                kind: 'clone',
                note: 'Deployed per artist as an EIP-1167 clone through the [factory](/docs/collections/contracts/factory). There is no single canonical address; substitute your collection address for `<COLLECTION_ADDRESS>` in the examples below.',
            },
            {name: 'SurfaceFactory', slug: 'factory', deploymentsKey: 'surfaceFactory', kind: 'singleton'},
            {
                name: 'FixedPriceMinter',
                slug: 'fixed-price-minter',
                deploymentsKey: null,
                kind: 'clone',
                note: 'Deployed per collection as an EIP-1167 clone: [`createSurface`](/docs/collections/contracts/factory#createsurface) wires one automatically and `SurfaceCreated.minter` records it. There is no single canonical address; substitute your collection\'s minter address for `<MINTER_ADDRESS>` in the examples below.',
            },
            {name: 'DefaultRenderer', slug: 'default-renderer', deploymentsKey: 'defaultRenderer', kind: 'singleton'},
            {name: 'RenderAssets', slug: 'render-assets', deploymentsKey: 'renderAssets', kind: 'singleton'},
            {
                name: 'ScriptyRenderer',
                slug: 'scripty-renderer',
                deploymentsKey: null,
                kind: 'clone',
                note: 'A bring-your-own generative renderer template, not a shared deployment. An artist deploys their own instance (one per work) with the work fixed in the constructor — immutable by construction — and points a collection\'s renderer slot at it, so there is no canonical address. The ABI below is the base template; see [Write a renderer](/docs/collections/guides/write-a-renderer).',
            },
            {
                name: 'IPriceStrategy',
                slug: 'i-price-strategy',
                deploymentsKey: null,
                kind: 'interface',
                note: 'Interface (ABI only), not a deployed contract. Implement it to install a custom pricing module in the price slot.',
            },
            {
                name: 'IRenderer',
                slug: 'i-renderer',
                deploymentsKey: null,
                kind: 'interface',
                note: 'Interface (ABI only), not a deployed contract. Implement it to install a custom renderer in the renderer slot.',
            },
            {
                name: 'ISurfaceView',
                slug: 'i-surface-view',
                deploymentsKey: null,
                kind: 'interface',
                note: 'Interface (ABI only): the read surface a collection exposes to its renderer, price strategy, and minters.',
            },
            {
                name: 'IPreviewRenderer',
                slug: 'i-preview-renderer',
                deploymentsKey: null,
                kind: 'interface',
                note: 'Interface (ABI only), OPTIONAL. Implement it on a renderer to support rendering a hypothetical token for a caller-supplied seed with no token needing to exist.',
            },
        ],
        guides: [
            {section: 'guides', slug: 'deploy-a-collection', file: 'collections/guides/deploy-a-collection.md'},
            {section: 'guides', slug: 'mint', file: 'collections/guides/mint.md'},
            {section: 'guides', slug: 'write-a-minter', file: 'collections/guides/write-a-minter.md'},
            {section: 'guides', slug: 'write-a-price-strategy', file: 'collections/guides/write-a-price-strategy.md'},
            {section: 'guides', slug: 'write-a-renderer', file: 'collections/guides/write-a-renderer.md'},
        ],
        referencePages: [
            {section: 'reference', slug: 'injection-convention', file: 'collections/reference/injection-convention.md'},
        ],
    },
    {
        id: 'auctions',
        title: 'Auctions',
        blurb: 'A per-owner onchain English-auction house for any ERC721: reserve pricing, an anti-snipe time-buffer extension, pull-payment refunds, and a protocol fee.',
        overview: 'auctions/overview.md',
        concepts: [
            {section: 'concepts', slug: 'auction-lifecycle', file: 'auctions/concepts/auction-lifecycle.md'},
        ],
        contracts: [
            {
                name: 'SovereignAuctionHouse',
                slug: 'sovereign-auction-house',
                deploymentsKey: null,
                kind: 'clone',
                note: 'Deployed per owner as an EIP-1167 clone through the [factory](/docs/auctions/contracts/auction-house-factory). There is no single canonical address; substitute your house address for `<AUCTION_HOUSE_ADDRESS>` in the examples below.',
            },
            {name: 'SovereignAuctionHouseFactory', slug: 'auction-house-factory', deploymentsKey: 'auctionHouseFactory', kind: 'singleton'},
        ],
        guides: [
            {section: 'guides', slug: 'deploy-an-auction-house', file: 'auctions/guides/deploy-an-auction-house.md'},
            {section: 'guides', slug: 'run-an-auction', file: 'auctions/guides/run-an-auction.md'},
            {section: 'guides', slug: 'bid-and-settle', file: 'auctions/guides/bid-and-settle.md'},
        ],
        referencePages: [],
    },
];

/** Shared groups: not tied to a single protocol. */
const SHARED_OFFCHAIN_PAGES: {slug: string; file: string}[] = [
    {slug: 'abis-and-manifest', file: 'offchain/abis-and-manifest.md'},
    {slug: 'ai-agents', file: 'offchain/ai-agents.md'},
];

const GROUP_TITLES: Record<string, string> = {
    introduction: 'Introduction',
    collections: 'Collections',
    auctions: 'Auctions',
    offchain: 'Off-chain',
};

/** Section order + labels within a group. '' is the group-level overview. */
const SECTION_ORDER = ['', 'concepts', 'contracts', 'guides', 'reference'];
const SECTION_TITLES: Record<string, string> = {
    '': '',
    concepts: 'Concepts',
    contracts: 'Contracts',
    guides: 'Guides',
    reference: 'Reference',
};

function pagePath(group: string, section: string, slug: string): string {
    return section ? `/docs/${group}/${section}/${slug}` : `/docs/${group}/${slug}`;
}

// ── ABI types + signature rendering ────────────────────────────────────

interface AbiParam {
    name: string;
    type: string;
    internalType?: string;
    indexed?: boolean;
    components?: AbiParam[];
}

interface AbiItem {
    type: 'function' | 'event' | 'error' | 'constructor' | 'receive' | 'fallback';
    name?: string;
    inputs?: AbiParam[];
    outputs?: AbiParam[];
    stateMutability?: 'pure' | 'view' | 'nonpayable' | 'payable';
}

function paramType(p: AbiParam): string {
    if (p.internalType) {
        return p.internalType.replace(/^(struct|enum|contract) /, '');
    }
    return p.type;
}

function renderParams(params: AbiParam[] | undefined, withIndexed = false): string {
    if (!params || params.length === 0) return '';
    return params
        .map((p) => {
            const indexed = withIndexed && p.indexed ? ' indexed' : '';
            const name = p.name ? ` ${p.name}` : '';
            return `${paramType(p)}${indexed}${name}`;
        })
        .join(', ');
}

function functionSignature(item: AbiItem): string {
    const mut = item.stateMutability;
    const mutStr = mut === 'nonpayable' ? '' : ` ${mut}`;
    const outs = item.outputs && item.outputs.length > 0 ? ` returns (${renderParams(item.outputs)})` : '';
    return `function ${item.name}(${renderParams(item.inputs)}) external${mutStr}${outs}`;
}

function eventSignature(item: AbiItem): string {
    return `event ${item.name}(${renderParams(item.inputs, true)})`;
}

function errorSignature(item: AbiItem): string {
    return `error ${item.name}(${renderParams(item.inputs)})`;
}

/** Disambiguation key used by prose for overloads: name(type1,type2). */
function overloadKey(item: AbiItem): string {
    return `${item.name}(${(item.inputs ?? []).map((p) => p.type).join(',')})`;
}

// ── Prose parsing ──────────────────────────────────────────────────────

interface ProseBlock {
    kind: 'function' | 'event' | 'error' | 'receive';
    key: string; // name or name(types)
    access: string | null;
    body: string;
    order: number;
}

interface ProseFile {
    frontmatter: Record<string, string>;
    summary: string;
    concepts: string | null;
    blocks: ProseBlock[];
}

function parseFrontmatter(src: string): {frontmatter: Record<string, string>; body: string} {
    const m = src.match(/^---\n([\s\S]*?)\n---\n?/);
    if (!m) return {frontmatter: {}, body: src};
    const frontmatter: Record<string, string> = {};
    for (const line of m[1].split('\n')) {
        const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
        if (kv) frontmatter[kv[1]] = kv[2].trim();
    }
    return {frontmatter, body: src.slice(m[0].length)};
}

function parseProse(path: string): ProseFile {
    const {frontmatter, body} = parseFrontmatter(readFileSync(path, 'utf8'));
    const lines = body.split('\n');
    interface Seg {
        level: number;
        heading: string;
        body: string[];
    }
    const segs: Seg[] = [];
    let cur: Seg | null = null;
    let inFence = false;
    for (const line of lines) {
        if (/^```/.test(line)) inFence = !inFence;
        const h = !inFence && line.match(/^(#{1,2}) (.+)$/);
        if (h) {
            if (cur) segs.push(cur);
            cur = {level: h[1].length, heading: h[2].trim(), body: []};
        } else if (cur) {
            cur.body.push(line);
        } else if (line.trim() !== '') {
            throw new Error(`${path}: content before the first heading: "${line}"`);
        }
    }
    if (cur) segs.push(cur);

    let summary = '';
    let concepts: string | null = null;
    const blocks: ProseBlock[] = [];
    let order = 0;
    for (const seg of segs) {
        const text = seg.body.join('\n').trim();
        if (seg.level === 1) {
            if (seg.heading === 'summary') summary = text;
            else if (seg.heading === 'concepts') concepts = text;
            else throw new Error(`${path}: unknown top-level section "# ${seg.heading}" (only summary/concepts allowed)`);
            continue;
        }
        if (seg.heading === 'receive') {
            const {access, rest} = extractAccess(text);
            blocks.push({kind: 'receive', key: 'receive', access, body: rest, order: order++});
            continue;
        }
        const m = seg.heading.match(/^(function|event|error) (\w+)(\([\w\s,[\]]*\))?$/);
        if (!m) throw new Error(`${path}: malformed block heading "## ${seg.heading}"`);
        const kind = m[1] as ProseBlock['kind'];
        const key = m[3] ? `${m[2]}${m[3].replace(/\s+/g, '')}` : m[2];
        const {access, rest} = extractAccess(text);
        blocks.push({kind, key, access, body: rest, order: order++});
    }
    if (!summary) throw new Error(`${path}: missing "# summary" section`);
    return {frontmatter, summary, concepts, blocks};
}

function extractAccess(text: string): {access: string | null; rest: string} {
    const m = text.match(/^access:\s*(.+)\n?/);
    if (!m) return {access: null, rest: text};
    return {access: m[1].trim(), rest: text.slice(m[0].length).trim()};
}

// ── Address substitution (pre-deploy tolerant) ─────────────────────────

const pendingKeys = new Set<string>();

function screamingSnake(key: string): string {
    return key.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function resolveAddr(key: string | null): string | null {
    if (!key) return null;
    const v = DEPLOYMENTS[key];
    if (typeof v === 'string' && /^0x[0-9a-fA-F]{40}$/.test(v)) return v;
    return null;
}

function substituteTokens(text: string): string {
    return text.replace(/\{\{addr:(\w+)\}\}/g, (_, key: string) => {
        const addr = resolveAddr(key);
        if (addr) return addr;
        pendingKeys.add(key);
        return `<${screamingSnake(key)}_ADDRESS>`;
    });
}

// ── Page assembly ──────────────────────────────────────────────────────

interface BuiltPage {
    group: string;
    section: string;
    slug: string;
    path: string;
    title: string;
    description: string;
    markdown: string;
}

interface AccessRow {
    slug: string;
    fn: string;
    access: string;
}
interface IndexRow {
    slug: string;
    name: string;
    prose: string;
}

// Cross-cutting rows accumulate per protocol id.
const accessRows = new Map<string, AccessRow[]>();
const errorRows = new Map<string, IndexRow[]>();
const eventRows = new Map<string, IndexRow[]>();
function rowsFor<T>(map: Map<string, T[]>, id: string): T[] {
    let a = map.get(id);
    if (!a) map.set(id, (a = []));
    return a;
}

function firstSentence(text: string): string {
    const flat = text.replace(/\s+/g, ' ').trim();
    // First sentence, but keep the abbreviation dots in i.e./e.g. from ending it.
    const m = flat.match(/^.*?(?<!i\.e|e\.g)[.!?](?=\s|$)/i);
    const sentence = m ? m[0] : flat;
    const CAP = 320;
    if (sentence.length <= CAP) return sentence;
    return sentence.slice(0, CAP).replace(/\s+\S*$/, '') + '…';
}

function headerLine(page: ContractPage): string | null {
    if (page.kind === 'singleton') {
        const addr = resolveAddr(page.deploymentsKey);
        if (addr) return `\`${addr}\` · [view on evm.now](https://evm.now/address/${addr}?chainId=1) · Ethereum mainnet`;
        return `> Not yet deployed to Ethereum mainnet. The address lands here at launch; until then, examples use an \`<${screamingSnake(page.deploymentsKey ?? 'address')}_ADDRESS>\` placeholder.`;
    }
    return page.note ? `> ${page.note}` : null;
}

function buildContractPage(protocol: Protocol, page: ContractPage): BuiltPage {
    const abi = ABI_BY_NAME[page.name];
    const prosePath = join(PROSE_DIR, `${page.name}.md`);
    if (!abi) throw new Error(`no ABI registered for ${page.name}`);
    if (!existsSync(prosePath)) throw new Error(`missing prose supplement: ${prosePath}`);
    const prose = parseProse(prosePath);

    const fns = abi.filter((i) => i.type === 'function');
    const events = abi.filter((i) => i.type === 'event');
    const errors = abi.filter((i) => i.type === 'error');
    const hasReceive = abi.some((i) => i.type === 'receive');
    const nameCounts = new Map<string, number>();
    for (const f of fns) nameCounts.set(f.name!, (nameCounts.get(f.name!) ?? 0) + 1);

    function functionHeading(item: AbiItem): string {
        const overloaded = (nameCounts.get(item.name!) ?? 0) > 1;
        return overloaded ? `${item.name}(${(item.inputs ?? []).map((p) => p.type).join(', ')})` : item.name!;
    }

    const proseFor = new Map<string, ProseBlock>();
    for (const b of prose.blocks) {
        const mapKey = `${b.kind}:${b.key}`;
        if (proseFor.has(mapKey)) throw new Error(`${prosePath}: duplicate block ${mapKey}`);
        proseFor.set(mapKey, b);
    }

    const problems: string[] = [];
    const usedBlocks = new Set<string>();

    function lookup(kind: ProseBlock['kind'], item: AbiItem): ProseBlock | null {
        const overload = overloadKey(item);
        const byOverload = proseFor.get(`${kind}:${overload}`);
        if (byOverload) {
            usedBlocks.add(`${kind}:${overload}`);
            return byOverload;
        }
        if ((nameCounts.get(item.name!) ?? 0) > 1 && kind === 'function') {
            problems.push(`overloaded function ${item.name} needs a "## function ${overload}" block`);
            return null;
        }
        const byName = proseFor.get(`${kind}:${item.name!}`);
        if (byName) {
            usedBlocks.add(`${kind}:${item.name!}`);
            return byName;
        }
        problems.push(`missing "## ${kind} ${item.name}" block`);
        return null;
    }

    const writeFns: {item: AbiItem; block: ProseBlock | null}[] = [];
    const readFns: {item: AbiItem; block: ProseBlock | null}[] = [];
    for (const f of fns) {
        const block = lookup('function', f);
        const isWrite = f.stateMutability === 'nonpayable' || f.stateMutability === 'payable';
        if (isWrite && block && !block.access) {
            problems.push(`state-changing function ${f.name} has no "access:" line`);
        }
        (isWrite ? writeFns : readFns).push({item: f, block});
    }
    writeFns.sort((a, b) => (a.block?.order ?? 1e9) - (b.block?.order ?? 1e9));
    readFns.sort((a, b) => a.item.name!.localeCompare(b.item.name!));
    events.sort((a, b) => a.name!.localeCompare(b.name!));
    errors.sort((a, b) => a.name!.localeCompare(b.name!));

    let receiveBlock: ProseBlock | null = null;
    if (hasReceive) {
        receiveBlock = proseFor.get('receive:receive') ?? null;
        if (receiveBlock) usedBlocks.add('receive:receive');
        else problems.push('missing "## receive" block for the receive() function');
        if (receiveBlock && !receiveBlock.access) problems.push('receive() block has no "access:" line');
    }

    const eventBlocks = events.map((e) => ({item: e, block: lookup('event', e)}));
    const errorBlocks = errors.map((e) => ({item: e, block: lookup('error', e)}));

    for (const key of proseFor.keys()) {
        if (!usedBlocks.has(key)) problems.push(`prose block "${key}" matches nothing in the ABI`);
    }
    if (problems.length > 0) {
        throw new Error(`${page.name}: prose/ABI mismatch\n  - ${problems.join('\n  - ')}`);
    }

    const parts: string[] = [];
    parts.push(`# ${page.name}`);
    const header = headerLine(page);
    if (header) parts.push(header);
    parts.push(prose.summary);
    if (prose.concepts) {
        parts.push(`## Concepts`);
        parts.push(prose.concepts);
    }

    const ac = rowsFor(accessRows, protocol.id);
    if (writeFns.length > 0 || hasReceive) {
        parts.push(`## Write functions`);
        for (const {item, block} of writeFns) {
            const heading = functionHeading(item);
            parts.push(`### ${heading}`);
            parts.push('```solidity\n' + functionSignature(item) + '\n```');
            parts.push(`**Access:** ${block!.access}`);
            if (block!.body) parts.push(block!.body);
            ac.push({slug: page.slug, fn: heading, access: block!.access!});
        }
        if (hasReceive && receiveBlock) {
            parts.push(`### receive`);
            parts.push('```solidity\nreceive() external payable\n```');
            parts.push(`**Access:** ${receiveBlock.access}`);
            if (receiveBlock.body) parts.push(receiveBlock.body);
            ac.push({slug: page.slug, fn: 'receive', access: receiveBlock.access!});
        }
    }

    if (readFns.length > 0) {
        parts.push(`## Read functions`);
        for (const {item, block} of readFns) {
            parts.push(`### ${functionHeading(item)}`);
            parts.push('```solidity\n' + functionSignature(item) + '\n```');
            if (block!.body) parts.push(block!.body);
        }
    }

    if (eventBlocks.length > 0) {
        const er = rowsFor(eventRows, protocol.id);
        parts.push(`## Events`);
        for (const {item, block} of eventBlocks) {
            parts.push(`### ${item.name}`);
            parts.push('```solidity\n' + eventSignature(item) + '\n```');
            if (block!.body) parts.push(block!.body);
            er.push({slug: page.slug, name: item.name!, prose: firstSentence(block!.body)});
        }
    }

    if (errorBlocks.length > 0) {
        const err = rowsFor(errorRows, protocol.id);
        parts.push(`## Errors`);
        for (const {item, block} of errorBlocks) {
            parts.push(`**\`${errorSignature(item).replace(/^error /, '')}\`**`);
            parts.push(block!.body);
            err.push({slug: page.slug, name: item.name!, prose: firstSentence(block!.body)});
        }
    }

    const markdown = substituteTokens(parts.join('\n\n') + '\n');
    return {
        group: protocol.id,
        section: 'contracts',
        slug: page.slug,
        path: pagePath(protocol.id, 'contracts', page.slug),
        title: prose.frontmatter.title || page.name,
        description: firstSentence(prose.summary),
        markdown,
    };
}

function buildHandPage(group: string, section: string, slug: string, file: string): BuiltPage {
    const path = join(PAGES_DIR, file);
    if (!existsSync(path)) throw new Error(`missing hand-written page: ${path}`);
    const {frontmatter, body} = parseFrontmatter(readFileSync(path, 'utf8'));
    if (!frontmatter.title) throw new Error(`${path}: frontmatter needs a title`);
    const markdown = substituteTokens(body.trim() + '\n');
    const h1 = markdown.match(/^# (.+)$/m);
    return {
        group,
        section,
        slug,
        path: pagePath(group, section, slug),
        title: frontmatter.title,
        description: frontmatter.description || (h1 ? h1[1] : frontmatter.title),
        markdown,
    };
}

// ── Generated pages: addresses + per-protocol cross-cutting indexes ─────

function buildAddressesPage(): BuiltPage {
    const parts: string[] = ['# Addresses'];
    const anyDeployed = PROTOCOLS.some((p) => p.contracts.some((c) => resolveAddr(c.deploymentsKey)));
    parts.push(
        anyDeployed
            ? `The shared singletons of each PND onchain protocol on Ethereum mainnet (chain id ${DEPLOYMENTS.chainId}). Per-owner clones (an artist collection, an auction house) are deployed through a factory and have no entry here; look their address up on-chain.`
            : `The PND onchain protocols are pre-deploy. These are the shared singletons; their addresses land here at launch. Per-owner clones (an artist collection, an auction house) are deployed through a factory, so they have no entry in these tables.`,
    );
    for (const proto of PROTOCOLS) {
        const singles = proto.contracts.filter((c) => c.deploymentsKey);
        if (singles.length === 0) continue;
        parts.push(`## ${proto.title}`);
        const rows = ['| Contract | Address | Docs |', '| --- | --- | --- |'];
        for (const c of singles) {
            const addr = resolveAddr(c.deploymentsKey);
            const cell = addr ? `[\`${addr}\`](https://evm.now/address/${addr}?chainId=1)` : '_pending deploy_';
            rows.push(`| ${c.name} | ${cell} | [reference](/docs/${proto.id}/contracts/${c.slug}) |`);
        }
        parts.push(rows.join('\n'));
    }
    parts.push('A machine-readable version of these tables (addresses + ABI + docs links) is served at [`/protocol-manifest.json`](/protocol-manifest.json).');
    return {
        group: 'introduction',
        section: '',
        slug: 'addresses',
        path: pagePath('introduction', '', 'addresses'),
        title: 'Addresses',
        description: 'The shared singletons of each PND onchain protocol, with ABI and reference links.',
        markdown: parts.join('\n\n') + '\n',
    };
}

function buildAccessControlPage(proto: Protocol): BuiltPage {
    const parts: string[] = ['# Access control'];
    parts.push(
        `Every state-changing function in the ${proto.title} contracts and who may call it. Generated from the per-contract references; the per-function pages carry the full behavior.`,
    );
    const rows = rowsFor(accessRows, proto.id);
    // group by contract slug in contract order
    for (const c of proto.contracts) {
        const forC = rows.filter((r) => r.slug === c.slug);
        if (forC.length === 0) continue;
        parts.push(`## ${c.name}`);
        const table = ['| Function | Access |', '| --- | --- |'];
        for (const r of forC) {
            table.push(`| [\`${r.fn}\`](/docs/${proto.id}/contracts/${r.slug}#${anchor(r.fn)}) | ${r.access} |`);
        }
        parts.push(table.join('\n'));
    }
    return {
        group: proto.id,
        section: 'reference',
        slug: 'access-control',
        path: pagePath(proto.id, 'reference', 'access-control'),
        title: 'Access control',
        description: `Every state-changing function in the ${proto.title} contracts and who may call it.`,
        markdown: parts.join('\n\n') + '\n',
    };
}

function buildErrorsPage(proto: Protocol): BuiltPage {
    const parts: string[] = ['# Errors index'];
    parts.push(`Every custom error the ${proto.title} contracts can revert with, its contract, and the condition that raises it.`);
    const sorted = [...rowsFor(errorRows, proto.id)].sort((a, b) => a.name.localeCompare(b.name) || a.slug.localeCompare(b.slug));
    const slugName = new Map(proto.contracts.map((c) => [c.slug, c.name]));
    for (const r of sorted) {
        parts.push(`**\`${r.name}\`** · [${slugName.get(r.slug) ?? r.slug}](/docs/${proto.id}/contracts/${r.slug}#errors)\\\n${r.prose}`);
    }
    return {
        group: proto.id,
        section: 'reference',
        slug: 'errors',
        path: pagePath(proto.id, 'reference', 'errors'),
        title: 'Errors index',
        description: `Every custom error in the ${proto.title} contracts, its contract, and the condition that raises it.`,
        markdown: parts.join('\n\n') + '\n',
    };
}

function buildEventsPage(proto: Protocol): BuiltPage {
    const parts: string[] = ['# Events index'];
    parts.push(`Every event the ${proto.title} contracts emit, grouped by contract. Signatures and field meanings live on the per-contract pages.`);
    const rows = rowsFor(eventRows, proto.id);
    for (const c of proto.contracts) {
        const forC = rows.filter((r) => r.slug === c.slug);
        if (forC.length === 0) continue;
        parts.push(`## ${c.name}`);
        for (const r of forC) {
            parts.push(`**[\`${r.name}\`](/docs/${proto.id}/contracts/${r.slug}#${anchor(r.name)})** · ${r.prose}`);
        }
    }
    return {
        group: proto.id,
        section: 'reference',
        slug: 'events',
        path: pagePath(proto.id, 'reference', 'events'),
        title: 'Events index',
        description: `Every event the ${proto.title} contracts emit, grouped by contract.`,
        markdown: parts.join('\n\n') + '\n',
    };
}

// ── Anchors (must match the app renderer's slugify) ────────────────────

function anchor(heading: string): string {
    return heading
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .trim()
        .replace(/\s+/g, '-');
}

// ── Markdown → HTML (pre-rendered at generation time) ──────────────────

interface TocEntry {
    depth: number;
    text: string;
    id: string;
}

interface RenderedPage {
    group: string;
    section: string;
    slug: string;
    title: string;
    description: string;
    html: string;
    toc: TocEntry[];
}

function escapeHtml(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function renderPageHtml(hl: Highlighter, page: BuiltPage): RenderedPage {
    const toc: TocEntry[] = [];
    const usedIds = new Map<string, number>();
    const loadedLangs = new Set(hl.getLoadedLanguages());
    const marked = new Marked({gfm: true});
    marked.use({
        renderer: {
            heading({tokens, depth, text}) {
                const inline = this.parser.parseInline(tokens);
                const base = anchor(text);
                const seen = usedIds.get(base) ?? 0;
                usedIds.set(base, seen + 1);
                const id = seen === 0 ? base : `${base}-${seen}`;
                if (depth === 2 || depth === 3) toc.push({depth, text, id});
                return `<h${depth} id="${id}"><a class="doc-anchor" href="#${id}">${inline}</a></h${depth}>\n`;
            },
            image({href, text}) {
                const m = href.match(/^\.\.\/_assets\/([\w-]+\.svg)$/);
                if (!m) return `<img src="${href}" alt="${escapeHtml(text)}" />`;
                const assetPath = join(ASSETS_DIR, m[1]);
                if (!existsSync(assetPath)) throw new Error(`missing diagram asset: ${assetPath}`);
                let svg = readFileSync(assetPath, 'utf8').replace(/<\?xml[^>]*\?>\s*/, '');
                const vb = svg.match(/viewBox="0 0 (\d+(?:\.\d+)?) (\d+(?:\.\d+)?)"/);
                if (!vb) throw new Error(`${assetPath}: svg needs a "0 0 w h" viewBox`);
                const maxW = Math.round(parseFloat(vb[1]) * 1.1);
                svg = svg.replace('<svg ', `<svg aria-label="${escapeHtml(text)}" `);
                return `<figure class="doc-figure" style="max-width:${maxW}px">${svg}</figure>\n`;
            },
            code({text, lang}) {
                const language = lang && loadedLangs.has(lang) ? lang : null;
                const body = language
                    ? hl.codeToHtml(text, {
                          lang: language,
                          themes: {light: 'github-light', dark: 'github-dark'},
                          defaultColor: 'light',
                      })
                    : `<pre class="shiki"><code>${escapeHtml(text)}</code></pre>`;
                const langTag = lang ? `<span class="doc-code-lang">${escapeHtml(lang)}</span>` : '';
                return `<div class="doc-code">${langTag}<button class="doc-copy" type="button" aria-label="Copy code">copy</button>${body}</div>\n`;
            },
        },
    });
    const html = marked.parse(page.markdown, {async: false}) as string;
    return {
        group: page.group,
        section: page.section,
        slug: page.slug,
        title: page.title,
        description: page.description,
        html,
        toc,
    };
}

// ── Search index ───────────────────────────────────────────────────────

interface SearchEntry {
    path: string;
    page: string;
    heading: string;
    anchor: string;
    text: string;
}

function stripMarkdown(md: string): string {
    return md
        .replace(/```[\s\S]*?```/g, ' ')
        .replace(/`([^`]*)`/g, '$1')
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/^#+ /gm, '')
        .replace(/[*_>|]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

function indexPage(page: BuiltPage): SearchEntry[] {
    const entries: SearchEntry[] = [];
    const segments = page.markdown.split(/^(?=#{1,3} )/m);
    for (const seg of segments) {
        const h = seg.match(/^(#{1,3}) (.+)\n/);
        const heading = h ? h[2].trim() : page.title;
        const body = stripMarkdown(h ? seg.slice(h[0].length) : seg);
        if (!body && !h) continue;
        entries.push({
            path: page.path,
            page: page.title,
            heading,
            anchor: h && h[1].length > 1 ? anchor(heading) : '',
            text: body.slice(0, 300),
        });
    }
    return entries;
}

// ── Main ───────────────────────────────────────────────────────────────

async function main() {
    const pages: BuiltPage[] = [];

    // Introduction (shared): overview, addresses (generated), conventions.
    pages.push(buildHandPage('introduction', '', 'overview', 'introduction/overview.md'));
    pages.push(buildAddressesPage());
    pages.push(buildHandPage('introduction', '', 'conventions', 'introduction/conventions.md'));

    // Each protocol: overview, concepts, contracts, guides, then reference indexes.
    for (const proto of PROTOCOLS) {
        pages.push(buildHandPage(proto.id, '', 'overview', proto.overview));
        for (const c of proto.concepts) pages.push(buildHandPage(proto.id, c.section, c.slug, c.file));
        for (const cp of proto.contracts) pages.push(buildContractPage(proto, cp));
        for (const g of proto.guides) pages.push(buildHandPage(proto.id, g.section, g.slug, g.file));
        pages.push(buildAccessControlPage(proto));
        pages.push(buildErrorsPage(proto));
        pages.push(buildEventsPage(proto));
        for (const rp of proto.referencePages) pages.push(buildHandPage(proto.id, rp.section, rp.slug, rp.file));
    }

    // Off-chain (shared).
    for (const p of SHARED_OFFCHAIN_PAGES) pages.push(buildHandPage('offchain', '', p.slug, p.file));

    // Write final markdown tree (wipe generated group dirs, keep _prose/_pages/_assets).
    for (const e of readdirSync(OUT_DIR, {withFileTypes: true})) {
        if (e.isDirectory() && !e.name.startsWith('_')) rmSync(join(OUT_DIR, e.name), {recursive: true, force: true});
    }
    for (const p of pages) {
        const rel = p.path.slice('/docs/'.length);
        const outFile = join(OUT_DIR, `${rel}.md`);
        mkdirSync(dirname(outFile), {recursive: true});
        const isContractRef = p.section === 'contracts';
        const banner = GENERATED_BANNER(isContractRef ? `_prose/ + @pin/abi` : `_pages/`);
        writeFileSync(outFile, banner + p.markdown);
    }

    // Manifest: groups → sections → items. Group order = first appearance.
    const groupOrder: string[] = [];
    for (const p of pages) if (!groupOrder.includes(p.group)) groupOrder.push(p.group);
    const manifest = {
        title: REFERENCE_TITLE,
        groups: groupOrder.map((gid) => {
            const gpages = pages.filter((p) => p.group === gid);
            const sectionIds: string[] = [];
            for (const p of gpages) if (!sectionIds.includes(p.section)) sectionIds.push(p.section);
            sectionIds.sort((a, b) => SECTION_ORDER.indexOf(a) - SECTION_ORDER.indexOf(b));
            return {
                id: gid,
                title: GROUP_TITLES[gid] ?? gid,
                sections: sectionIds.map((sid) => ({
                    id: sid,
                    title: SECTION_TITLES[sid] ?? sid,
                    items: gpages
                        .filter((p) => p.section === sid)
                        .map((p) => ({title: p.title, slug: p.slug, path: p.path, description: p.description})),
                })),
            };
        }),
    };
    mkdirSync(APP_DOCS_DIR, {recursive: true});
    writeFileSync(join(APP_DOCS_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

    // Pre-rendered HTML content module (imported by the app's /docs pages).
    const hl = await createHighlighter({
        themes: ['github-light', 'github-dark'],
        langs: ['solidity', 'typescript', 'javascript', 'bash', 'json', 'graphql'],
    });
    const content: Record<string, RenderedPage> = {};
    for (const p of pages) content[p.path.slice('/docs/'.length)] = renderPageHtml(hl, p);
    writeFileSync(join(APP_DOCS_DIR, 'content.json'), JSON.stringify(content) + '\n');

    // Search index.
    const search = pages.flatMap(indexPage);
    mkdirSync(APP_PUBLIC_DIR, {recursive: true});
    writeFileSync(join(APP_PUBLIC_DIR, 'docs-search-index.json'), JSON.stringify(search) + '\n');

    // Public ABIs (JSON copies of the checked-in @pin/abi exports).
    const publicAbiDir = join(APP_PUBLIC_DIR, 'abis');
    rmSync(publicAbiDir, {recursive: true, force: true});
    mkdirSync(publicAbiDir, {recursive: true});
    for (const [name, abi] of Object.entries(ABI_BY_NAME)) {
        writeFileSync(join(publicAbiDir, `${name}.json`), JSON.stringify(abi, null, 2) + '\n');
    }

    // Protocol manifest: contracts grouped by protocol.
    const protocolManifest = {
        name: 'PND onchain protocols',
        origin: SITE_ORIGIN,
        chainId: DEPLOYMENTS.chainId,
        docs: '/docs',
        llms: '/llms.txt',
        protocols: Object.fromEntries(
            PROTOCOLS.map((proto) => [
                proto.id,
                {
                    title: proto.title,
                    docs: `/docs/${proto.id}/overview`,
                    contracts: Object.fromEntries(
                        proto.contracts.map((c) => {
                            const built = pages.find((x) => x.group === proto.id && x.section === 'contracts' && x.slug === c.slug)!;
                            return [
                                c.name,
                                {
                                    address: resolveAddr(c.deploymentsKey),
                                    kind: c.kind,
                                    abi: `/abis/${c.name}.json`,
                                    docs: c.slug ? `/docs/${proto.id}/contracts/${c.slug}` : undefined,
                                    role: built.description,
                                },
                            ];
                        }),
                    ),
                },
            ]),
        ),
    };
    writeFileSync(join(APP_PUBLIC_DIR, 'protocol-manifest.json'), JSON.stringify(protocolManifest, null, 2) + '\n');

    // llms.txt
    const llms: string[] = [];
    llms.push('# PND onchain protocols');
    llms.push('');
    llms.push(
        '> The onchain protocols PND ships for artists. Each is a self-contained set of contracts with an API reference below. Collections are artist-owned ERC721 contracts built on a thin token core where every mint goes through an authorized minter, with a canonical fixed-price/referral minter wired by the factory. Auctions are per-owner English-auction houses for any ERC721. More protocols land here as they ship.',
    );
    llms.push('');
    llms.push(`Machine-readable addresses + ABIs: ${SITE_ORIGIN}/protocol-manifest.json (ABIs under ${SITE_ORIGIN}/abis/).`);
    llms.push('');
    for (const group of manifest.groups) {
        llms.push(`## ${group.title}`);
        llms.push('');
        for (const section of group.sections) {
            for (const item of section.items) {
                llms.push(`- [${item.title}](${SITE_ORIGIN}${item.path}): ${item.description}`);
            }
        }
        llms.push('');
    }
    writeFileSync(join(APP_PUBLIC_DIR, 'llms.txt'), llms.join('\n'));

    if (pendingKeys.size > 0) {
        console.log(`Pre-deploy: ${pendingKeys.size} address placeholder(s) unresolved (${[...pendingKeys].join(', ')}). Fill contracts/deployments.mainnet.json at launch.`);
    }
    const totalAccess = [...accessRows.values()].reduce((n, a) => n + a.length, 0);
    const totalErrors = [...errorRows.values()].reduce((n, a) => n + a.length, 0);
    const totalEvents = [...eventRows.values()].reduce((n, a) => n + a.length, 0);
    console.log(
        `Generated ${pages.length} pages across ${manifest.groups.length} groups, ${search.length} search entries, ${totalAccess} access rows, ${totalErrors} errors, ${totalEvents} events.`,
    );
}

main().catch((e: unknown) => {
    console.error(e instanceof Error ? e.message : e);
    process.exit(1);
});
